<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcgnp1q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcgnp1q/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNcgnp1q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNcgnp1q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNcgnp1q\appProdProjectContainer([
    'container.build_hash' => 'Ncgnp1q',
    'container.build_id' => 'c2642c14',
    'container.build_time' => 1653293741,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcgnp1q');
